koreader/virdevenv

docker/ubuntu/baseimage/bootstrap.sh

Otherwise czmq fails, at least while cross-compiling.

[fix] Docker baseimage: add pkg-config

---

docker/ubuntu/baseimage/Makefile
docker/ubuntu/baseimage/bootstrap.sh

[Docker] baseimage: add libcairo2

---

docker/ubuntu/koappimage/Dockerfile
docker/ubuntu/koappimage/Makefile

Otherwise the build runs as root, which tar is not a fan of.

[fix, Docker] AppImage user

---

docker/ubuntu/baseimage-python/Dockerfile
docker/ubuntu/baseimage-python/Makefile

Same as 9491e97702455313aa25062047b67dcc6b94651e
Results in `pthread_create() failed, 1 EPERM` error, indicating the baseimage-python image accidentally ran as root.

[fix, Docker] baseimage-python user

---

docker/ubuntu/kopb/Dockerfile
docker/ubuntu/kopb/Makefile

Cf. https://github.com/koreader/koreader-base/pull/765 because the
entire toolchain wasn't even actually being used! D-:
Still needs adjustments in kodev in front.

[Docker] kopb: slim down a bit by removing .git and locales

---

docker/ubuntu/koandroid/Makefile
docker/ubuntu/koandroid/build_android_tc.sh
docker/ubuntu/koandroid/fetch_android_tc.sh

Cf. https://github.com/koreader/koreader/pull/5096

Docker/Android: bump TC creation

---

docker/ubuntu/baseimage-python/Dockerfile
docker/ubuntu/baseimage-python/Makefile
docker/ubuntu/baseimage/Makefile
docker/ubuntu/baseimage/bootstrap.sh
docker/ubuntu/koappimage/Dockerfile
docker/ubuntu/koappimage/Makefile

See https://github.com/koreader/koreader/pull/5238#issuecomment-523675211
Even if a fix is implemented upstream soon, it'd be years before we could use a precompiled binary anyway.

Docker baseimage: add custom xgettext build

---

docker/ubuntu/baseimage-clang/Dockerfile
docker/ubuntu/baseimage-clang/Makefile
docker/ubuntu/baseimage-clang/clang8.list
docker/ubuntu/baseimage-clang/clang9.list

Release notes: <http://releases.llvm.org/9.0.0/tools/clang/docs/ReleaseNotes.html>
**DON'T MERGE UNTIL THE POINT RELEASE IS OUT** (and also out on `deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main`)
Clang 9 compiler-rt is broken, see https://reviews.llvm.org/D67628
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/45)

Docker/baseimage-clang: Update to Clang 9

---

docker/ubuntu/kopb/Dockerfile
docker/ubuntu/kopb/Makefile
docker/ubuntu/kopb/build_pb_tc.sh

See <https://github.com/koreader/koxtoolchain/pull/22>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/49)

Use our own PocketBook TC instead of ancient gcc 4.8

---

.ci/script.sh

```
You are downloading ShellCheck from an outdated URL!
Please update to the new URL:
https://github.com/koalaman/shellcheck/releases/download/v0.5.0/shellcheck-v0.5.0.linux.x86_64.tar.xz
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/60)

Update ShellCheck URL and version

---

docker/ubuntu/baseimage-clang/Dockerfile
docker/ubuntu/baseimage/bootstrap.sh
docker/ubuntu/koandroid/fetch_android_tc.sh

An oversight for LuaJIT cross-compilation on newer systems.
Also swap in GCC 8 instead of 7 since apparently that's an easy option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/63)

[fix] Docker baseimage: add libc6-dev:i386

---

docker/ubuntu/baseimage/bootstrap.sh

Cf. https://github.com/koreader/koreader-base/pull/1375#issuecomment-848042842
Perhaps I overlooked something in what I tried previously but I'm not inclined to try to figure out what might be wrong if it Just Works™ with the default GCC 7 TCs.
```diff
diff --git a/docker/ubuntu/baseimage/bootstrap.sh b/docker/ubuntu/baseimage/bootstrap.sh
index 07a782d..9d8f669 100755
--- a/docker/ubuntu/baseimage/bootstrap.sh
+++ b/docker/ubuntu/baseimage/bootstrap.sh
@@ -40,8 +40,12 @@ apt-get install --no-install-recommends -y \
"${ARM_SF_TC[@]}" "${ARM_HF_TC[@]}" "${ARM64_TC[@]}" \
"${LUAJIT_DEPS[@]}"
-sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7
-sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave …
```

Docker base image: fix basic cross compile

---

docker/ubuntu/koandroid/Dockerfile

Otherwise ant pulls in default-jre-headless which is openjdk-11-jre-headless.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/65)

Docker koandroid: purposefully install openjdk-8-jre-headless as ant dependency

---

docker/ubuntu/baseimage/Dockerfile
docker/ubuntu/baseimage/install_lint.sh
docker/ubuntu/baseimage/install_luarocks.sh

This is part of work to also use Github actions as CI
Use distro luarocks
Install packages globally
Use latest busted
Dont install luacov-coveralls & luasec: we don't use them at all
There is no need to explicitly install luarocks dependencies
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/71)

Allow install scripts to be used by koreader CI

---

docker/ubuntu/baseimage/Dockerfile
docker/ubuntu/baseimage/install_lint.sh
docker/ubuntu/baseimage/install_luarocks.sh

Reverts koreader/virdevenv#71
Sorry, but I need this working.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/75)

Revert "Allow install scripts to be used by koreader CI"

---

docker/ubuntu/baseimage-18.04/Dockerfile
docker/ubuntu/baseimage-18.04/Makefile
docker/ubuntu/baseimage-20.04/Dockerfile
docker/ubuntu/baseimage-20.04/Makefile
docker/ubuntu/baseimage-clang/Dockerfile
docker/ubuntu/baseimage-clang/Makefile
docker/ubuntu/baseimage-python/Dockerfile
docker/ubuntu/baseimage-python/Makefile
docker/ubuntu/koandroid/Dockerfile
docker/ubuntu/koandroid/Makefile
docker/ubuntu/koappimage/Dockerfile
docker/ubuntu/koappimage/Makefile
docker/ubuntu/kobookeen/Dockerfile
docker/ubuntu/kobookeen/Makefile
docker/ubuntu/kocervantes/Dockerfile
docker/ubuntu/kocervantes/Makefile
docker/ubuntu/kokindle/Dockerfile
docker/ubuntu/kokindle/Makefile
docker/ubuntu/kokobo/Dockerfile
docker/ubuntu/kokobo/Makefile
docker/ubuntu/kopb/Dockerfile
docker/ubuntu/kopb/Makefile
docker/ubuntu/koremarkable/Dockerfile
docker/ubuntu/koremarkable/Makefile
docker/ubuntu/kout/Dockerfile
docker/ubuntu/kout/Makefile

Basic usage would look like:
```
USER=koreader REGISTRY=ghcr.io make build
USER=koreader REGISTRY=ghcr.io make push
```
With as a result:
https://github.com/orgs/koreader/packages
https://github.com/orgs/koreader/packages/container/package/kobase-clang
To be made public it would need to be associated with a repository.
For some background as to why I'm adding this:
https://news.ycombinator.com/item?id=35154025 (tl;dr Docker announced they would get rid of the free registry)
https://www.docker.com/developers/free-team-faq/ (tl;dr Docker reversed its plans a couple weeks later)
<hr>
Note that Google made a tool called `crane` that is supposed to be able to move images over between registries, so the main point of this PR may be little more than making it easier to decide where to push it …

Add REGISTRY variable for different Docker registries

---

docker/ubuntu/koandroid/Dockerfile
docker/ubuntu/koandroid/build_android_tc.sh
docker/ubuntu/koandroid/fetch_android_tc.sh

Since building the Android docker image normally relies on [koreader-base/toolchain/Makefile](https://github.com/koreader/koreader-base/blob/master/toolchain/Makefile), until https://github.com/koreader/koreader-base/pull/1620 is merged, I worked around the problem by overriding a few of the Makefile's variables…
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/86)

android: update to use NDK 23c

---

docker/ubuntu/koappimage/Dockerfile
docker/ubuntu/koappimage/Makefile

Forgot to update them…
What about the other images? The remarkable image is not used by the koreader & koreader-base CIs, but it's used on Gitlab to build the nightlies, so it should probably be updated. That leaves the debian ones, which are all still on 18.04.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/88)

appimage: fix tags (including base image)

---

docker/ubuntu/baseimage-20.04/Dockerfile
docker/ubuntu/baseimage-20.04/bashrc
docker/ubuntu/koandroid/Dockerfile
docker/ubuntu/scripts/install_x-tools.sh

Rational: makes mounting volumes much nicer, as there's no need to faff around with permissions: `docker run --user root -ti --rm -v $PWD:/src …`. Incidentally, also make the image usable on Github Actions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/97)

make baseimage usable as root

---

docker/ubuntu/baseimage-20.04/Dockerfile

- bump ccache, shellcheck & shfmt
- install cmakelint, meson, jq & ninjatracing (for build timings stats)
With the previous PR and this one, increase base image size by 37MB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/98)

baseimage: bump some tools + more tools

---

docker/ubuntu/Makefile
docker/ubuntu/baseimage-20.04/Dockerfile
docker/ubuntu/baseimage-20.04/settings.mk

- switch to pkgconf (from pkg-config, for `--env-only` support)
- install GCC plugin development package
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/112)

baseimage-20.04: ffi-cdecl support

---

docker/ubuntu/Makefile

For example: `make baseimage-20.04/latest`, to tag the current version as latest, without the need for building/pulling locally (the versioned image must already be available on the registry).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/113)

add make rules to tag image as latest
