koreader/virdevenv

- vm/ubuntu/README.md
- vm/ubuntu/Vagrantfile
This is a proper way of fixing it, right?
> Well, this one is pretty critical

- docker/ubuntu/baseimage/Makefile
- docker/ubuntu/baseimage/bootstrap.sh
> [fix] build Docker baseimage

- docker/ubuntu/kokindle/Makefile
- docker/ubuntu/kokindle/build_kindle_tc.sh
- docker/ubuntu/kokobo/Makefile
- docker/ubuntu/kokobo/build_kobo_tc.sh
See https://github.com/koreader/koreader/issues/3302 and https://github.com/koreader/koxtoolchain/pull/3
> Docker: minor TC update for C++ apps linking to libstdc++

- docker/ubuntu/kocervantes/Dockerfile
- docker/ubuntu/kocervantes/Makefile
- docker/ubuntu/kocervantes/build_cervantes_tc.sh
pinging @Frenzie for feedback :+1:
> add kocervantes

- docker/ubuntu/baseimage/.bashrc
- docker/ubuntu/baseimage/bootstrap.sh
- docker/ubuntu/baseimage/install_luarocks.sh
- docker/ubuntu/koandroid/build_android_tc.sh
- docker/ubuntu/kocervantes/build_cervantes_tc.sh
- docker/ubuntu/kokindle/build_kindle_tc.sh
- docker/ubuntu/kokobo/build_kobo_tc.sh
> ShellCheck fixes

- docker/ubuntu/baseimage/.bashrc
- docker/ubuntu/baseimage/Makefile
- docker/ubuntu/kocervantes/Dockerfile
- docker/ubuntu/kocervantes/Makefile
Supersedes https://github.com/koreader/virdevenv/pull/17
> [Docker] baseimage: forward-thinking PATH glob

- docker/ubuntu/baseimage/Makefile
- docker/ubuntu/baseimage/bootstrap.sh
It was a bug fixed in https://github.com/AppImage/AppImageKit/pull/863
> [Docker] revert adding libcairo

- docker/ubuntu/koandroid/Makefile
- docker/ubuntu/koandroid/build_android_tc.sh
- docker/ubuntu/koandroid/fetch_android_tc.sh
Necessary prerequisite for
<https://github.com/koreader/koreader/issues/4471>.
> [Docker] Update to Android NDK r15c

- docker/ubuntu/koappimage/Dockerfile
- docker/ubuntu/koappimage/Makefile
Cf. https://github.com/koreader/koreader/issues/4627 and https://github.com/koreader/koreader-base/pull/826
> [Docker] koappimage: add libx11-dev for libXss.so.1 dummy

- docker/ubuntu/koappimage/Dockerfile
- docker/ubuntu/koappimage/Makefile
Also see https://github.com/koreader/koreader/pull/4296
> [Docker] koappimage: base on kobase-python so it can be properly utilized for CI

- docker/ubuntu/baseimage-python/Dockerfile
- docker/ubuntu/baseimage-python/Makefile
- docker/ubuntu/baseimage/Makefile
- docker/ubuntu/baseimage/bootstrap.sh
- docker/ubuntu/koandroid/Dockerfile
- docker/ubuntu/koandroid/Makefile
- docker/ubuntu/koappimage/Dockerfile
- docker/ubuntu/koappimage/Makefile
- docker/ubuntu/kocervantes/Dockerfile
- docker/ubuntu/kocervantes/Makefile
- docker/ubuntu/kocervantes/build_cervantes_tc.sh
- docker/ubuntu/kokindle/Dockerfile
- docker/ubuntu/kokindle/Makefile
- docker/ubuntu/kokindle/build_kindle_tc.sh
- docker/ubuntu/kokobo/Dockerfile
- docker/ubuntu/kokobo/Makefile
- docker/ubuntu/kokobo/build_kobo_tc.sh
- docker/ubuntu/kopb/Dockerfile
- docker/ubuntu/kopb/Makefile
ninja mainly for faster builds in CI in front & of course also for hackers using the Docker image, cf. https://github.com/koreader/koreader-base/pull/861
koxtoolchain just because I'm pushing new images anyway, cf. https://github.com/koreader/koxtoolchain/pull/11
> Docker: add ninja & update koxtoolchain

- docker/ubuntu/kout/Dockerfile
- docker/ubuntu/kout/Makefile
We want to use newer CMake after all.
Cf. #35.
> [fix, Docker] Add Ubuntu Touch image

- docker/ubuntu/baseimage-clang/Dockerfile
- docker/ubuntu/baseimage-clang/Makefile
- docker/ubuntu/baseimage-clang/clang7.list
Cf. https://github.com/koreader/koreader-base/pull/897#issuecomment-485124899
> Docker: add Clang image 

- docker/ubuntu/baseimage-clang/Dockerfile
- docker/ubuntu/baseimage-clang/Makefile
- docker/ubuntu/baseimage-python/Dockerfile
- docker/ubuntu/baseimage-python/Makefile
- docker/ubuntu/baseimage/Makefile
- docker/ubuntu/baseimage/install_luarocks.sh
- docker/ubuntu/koappimage/Dockerfile
- docker/ubuntu/koappimage/Makefile
Cf. https://github.com/koreader/koreader-base/issues/905
> [Docker] Bump luajit-luarocks to latest commit and busted to v2.0.rc13-0

- .hadolint.yaml
- .travis.yml
- docker/ubuntu/baseimage-clang/Dockerfile
- docker/ubuntu/baseimage-clang/Makefile
- docker/ubuntu/baseimage/Dockerfile
- docker/ubuntu/koandroid/Dockerfile
- docker/ubuntu/kocervantes/Dockerfile
- docker/ubuntu/kokindle/Dockerfile
- docker/ubuntu/kokobo/Dockerfile
- docker/ubuntu/kopb/Dockerfile
Automated lint for Dockerfile best practices.
See <https://github.com/hadolint/hadolint>.
> [CI] Add hadolint for Dockerfile

- docker/ubuntu/baseimage-clang/Dockerfile
- docker/ubuntu/baseimage-clang/clang7.list
- docker/ubuntu/baseimage-clang/clang8.list
Release notes: <http://releases.llvm.org/8.0.0/tools/clang/docs/ReleaseNotes.html>
> Docker/baseimage-clang: switch to Clang 8

- docker/ubuntu/baseimage-clang/Makefile
- docker/ubuntu/baseimage-python/Makefile
- docker/ubuntu/baseimage/Makefile
- docker/ubuntu/koandroid/Makefile
- docker/ubuntu/koappimage/Makefile
- docker/ubuntu/kocervantes/Makefile
- docker/ubuntu/kokindle/Makefile
- docker/ubuntu/kokobo/Makefile
- docker/ubuntu/kopb/Makefile
- docker/ubuntu/kout/Makefile
Cf. https://github.com/koreader/koreader-base/pull/875
> [chore] Add Makefile phonies

- docker/ubuntu/baseimage-clang/Dockerfile
- docker/ubuntu/baseimage-clang/Makefile
- docker/ubuntu/baseimage-python/Dockerfile
- docker/ubuntu/baseimage-python/Makefile
- docker/ubuntu/baseimage/Makefile
- docker/ubuntu/baseimage/bootstrap.sh
- docker/ubuntu/koandroid/Dockerfile
- docker/ubuntu/koandroid/Makefile
- docker/ubuntu/koappimage/Dockerfile
- docker/ubuntu/koappimage/Makefile
- docker/ubuntu/kocervantes/Dockerfile
- docker/ubuntu/kocervantes/Makefile
- docker/ubuntu/kocervantes/build_cervantes_tc.sh
- docker/ubuntu/kokindle/Dockerfile
- docker/ubuntu/kokindle/Makefile
- docker/ubuntu/kokindle/build_kindle_tc.sh
- docker/ubuntu/kokobo/Dockerfile
- docker/ubuntu/kokobo/Makefile
- docker/ubuntu/kokobo/build_kobo_tc.sh
- docker/ubuntu/kopb/Dockerfile
- docker/ubuntu/kopb/Makefile
- docker/ubuntu/kout/Dockerfile
- docker/ubuntu/kout/Makefile
See discussion in <https://github.com/koreader/koreader-base/pull/1025#issuecomment-570556188>.
Also includes TC update to <https://github.com/koreader/koxtoolchain/commit/576338981f3ba6723801c3056ae2c7ca33915181>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/46)
> [chore] Add ragel to Docker images

- docker/ubuntu/koremarkable/Dockerfile
- docker/ubuntu/koremarkable/Makefile
- docker/ubuntu/koremarkable/build_remarkable_tc.sh
untested for the sake of my poor bandwidth :+1:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/47)
> add docker image for reMarkable

- docker/ubuntu/baseimage/Makefile
- docker/ubuntu/baseimage/install_luarocks.sh
Cf. https://github.com/koreader/koreader-base/issues/956
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/48)
> baseimage: update to busted 2.0

- docker/ubuntu/kobookeen/Dockerfile
- docker/ubuntu/kobookeen/Makefile
- docker/ubuntu/kobookeen/build_bookeen_tc.sh
See https://github.com/koreader/koxtoolchain/pull/26 and https://github.com/koreader/koreader/issues/6043
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/50)
> Docker: add Bookeen image

- docker/ubuntu/baseimage-clang/Dockerfile
- docker/ubuntu/baseimage-clang/Makefile
- docker/ubuntu/baseimage-clang/clang10.list
- docker/ubuntu/baseimage-clang/clang9.list
In response to <https://github.com/koreader/crengine/pull/350#issuecomment-651919872>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/52)
> Docker/baseimage-clang: Update to Clang 10

- docker/ubuntu/koandroid/Makefile
- docker/ubuntu/koandroid/build_android_tc.sh
- docker/ubuntu/koandroid/fetch_android_tc.sh
Requires https://github.com/koreader/koreader-base/pull/1230
Requires https://github.com/koreader/android-luajit-launcher/pull/253
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/54)
> Add 64 bit ABIs, bump SDK_VER

- docker/ubuntu/baseimage/Makefile
- docker/ubuntu/baseimage/bootstrap.sh
- vm/ubuntu/bootstrap.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/56)
> add linux aarch64

- docker/ubuntu/baseimage-clang/Dockerfile
Hadolint likes it, and so do I. ;-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/61)
> Add --progress=dot:giga to wget invocation

- docker/ubuntu/baseimage/Dockerfile
- docker/ubuntu/baseimage/Makefile
- docker/ubuntu/baseimage/bootstrap.sh
- docker/ubuntu/koandroid/build_android_tc.sh
Some minor prep to be finalized after 2021.03 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/57)
> Update to Ubuntu 18.04

- docker/ubuntu/baseimage-clang/Dockerfile
- docker/ubuntu/baseimage-clang/Makefile
- docker/ubuntu/baseimage-clang/clang10.list
- docker/ubuntu/baseimage-clang/clang12.list
- docker/ubuntu/baseimage-python/Dockerfile
- docker/ubuntu/baseimage-python/Makefile
- docker/ubuntu/koandroid/Dockerfile
- docker/ubuntu/koandroid/Makefile
- docker/ubuntu/koappimage/Dockerfile
- docker/ubuntu/koappimage/Makefile
- docker/ubuntu/kobookeen/Dockerfile
- docker/ubuntu/kobookeen/Makefile
- docker/ubuntu/kobookeen/build_bookeen_tc.sh
- docker/ubuntu/kocervantes/Dockerfile
- docker/ubuntu/kocervantes/Makefile
- docker/ubuntu/kocervantes/build_cervantes_tc.sh
- docker/ubuntu/kokindle/Dockerfile
- docker/ubuntu/kokindle/Makefile
- docker/ubuntu/kokindle/build_kindle_tc.sh
- docker/ubuntu/kokobo/Dockerfile
- docker/ubuntu/kokobo/Makefile
- docker/ubuntu/kokobo/build_kobo_tc.sh
- docker/ubuntu/kopb/Dockerfile
- docker/ubuntu/kopb/Makefile
- docker/ubuntu/kopb/build_pb_tc.sh
- docker/ubuntu/koremarkable/Dockerfile
- docker/ubuntu/koremarkable/Makefile
- docker/ubuntu/koremarkable/build_remarkable_tc.sh
- docker/ubuntu/kout/Dockerfile
- docker/ubuntu/kout/Makefile
Update everything to Ubuntu 18.04 as well as other pertinent updates (e.g., Clang 12, latest koxtoolchain, clickable). See commit messages for more details.
--------
Android, Kindle and PocketBook aren't done yet at the time of writing. For Kindle and PB cf. https://github.com/koreader/koxtoolchain/issues/30 and https://github.com/koreader/koxtoolchain/issues/31.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/62)
> Docker: Ubuntu 18.04 update

- docker/ubuntu/baseimage/Makefile
- docker/ubuntu/baseimage/bootstrap.sh
Cf. https://github.com/koreader/koreader/issues/7778#issuecomment-853383260, https://github.com/koreader/koreader/pull/7804, https://github.com/koreader/koreader/issues/7805
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/66)
> Docker baseimage: add fakeroot

- docker/ubuntu/baseimage-clang/Dockerfile
- docker/ubuntu/baseimage-clang/Makefile
- docker/ubuntu/baseimage-python/Dockerfile
- docker/ubuntu/baseimage-python/Makefile
- docker/ubuntu/baseimage/Dockerfile
- docker/ubuntu/baseimage/Makefile
- docker/ubuntu/baseimage/install_lint.sh
- docker/ubuntu/koandroid/Dockerfile
- docker/ubuntu/koandroid/Makefile
- docker/ubuntu/koappimage/Dockerfile
- docker/ubuntu/koappimage/Makefile
- docker/ubuntu/kobookeen/Dockerfile
- docker/ubuntu/kobookeen/Makefile
- docker/ubuntu/kobookeen/build_bookeen_tc.sh
- docker/ubuntu/kocervantes/Dockerfile
- docker/ubuntu/kocervantes/Makefile
- docker/ubuntu/kocervantes/build_cervantes_tc.sh
- docker/ubuntu/kokindle/Dockerfile
- docker/ubuntu/kokindle/Makefile
- docker/ubuntu/kokindle/build_kindle_tc.sh
- docker/ubuntu/kokobo/Dockerfile
- docker/ubuntu/kokobo/Makefile
- docker/ubuntu/kokobo/build_kobo_tc.sh
- docker/ubuntu/kopb/Dockerfile
- docker/ubuntu/kopb/Makefile
- docker/ubuntu/kopb/build_pb_tc.sh
- docker/ubuntu/koremarkable/Dockerfile
- docker/ubuntu/koremarkable/Makefile
- docker/ubuntu/koremarkable/build_remarkable_tc.sh
Needed because of the Let's Encrypt root certificate update. Also integrates ShellCheck and shfmt to simplify maintenance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/68)
> New Docker image for root certificates and toolchain

- README.md
Closes #72.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/74)
> Add warning to Docker hack

- docker/ubuntu/baseimage-clang/Dockerfile
- docker/ubuntu/baseimage-clang/Makefile
- docker/ubuntu/baseimage-clang/clang12.list
- docker/ubuntu/baseimage-clang/clang14.list
- docker/ubuntu/baseimage-clang/clang16.list
- docker/ubuntu/koandroid/Dockerfile
- docker/ubuntu/koandroid/Makefile
- docker/ubuntu/kobookeen/Dockerfile
- docker/ubuntu/kobookeen/Makefile
- docker/ubuntu/kocervantes/Dockerfile
- docker/ubuntu/kocervantes/Makefile
- docker/ubuntu/kokindle/Dockerfile
- docker/ubuntu/kokindle/Makefile
- docker/ubuntu/kokobo/Dockerfile
- docker/ubuntu/kokobo/Makefile
- docker/ubuntu/kopb/Dockerfile
- docker/ubuntu/kopb/Makefile
- docker/ubuntu/koremarkable/Dockerfile
- docker/ubuntu/koremarkable/Makefile
Using 18.04 for all the cross stuff, cf. #79.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/80)
> Docker updates to CMake 3.16

- docker/ubuntu/koandroid/Dockerfile
- docker/ubuntu/koandroid/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/84)
> Update Docker Android image to use the Ubuntu 22.04 baseimage

- docker/ubuntu/koandroid/Dockerfile
- docker/ubuntu/koandroid/Makefile
Reverts koreader/virdevenv#84
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/85)
> Revert "Update Docker Android image to use the Ubuntu 22.04 baseimage"

- docker/ubuntu/koappimage/Dockerfile
- docker/ubuntu/koappimage/Makefile
- docker/ubuntu/kokobo/Dockerfile
- docker/ubuntu/koremarkable/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/91)
> appimage: fix user

- docker/ubuntu/baseimage-clang/Dockerfile
- docker/ubuntu/baseimage-clang/Makefile
So we actually benefit from it (slightly reduced final image size).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/92)
> baseimage-clang: fix build stage

- docker/ubuntu/baseimage-20.04/Dockerfile
- docker/ubuntu/baseimage-20.04/Makefile
- docker/ubuntu/kodeb/Dockerfile
- docker/ubuntu/kodeb/Makefile
Close #95.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/96)
> debian: add dedicated image for building debian packages

- docker/ubuntu/koandroid/Dockerfile
Reduce image size by 410MB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/99)
> android: trim image + install uber apk signer

- docker/ubuntu/scripts/install_x-tools.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/100)
> scripts: fix ownership of installed x-tools

- docker/ubuntu/koandroid/Dockerfile
- docker/ubuntu/koandroid/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/102)
> android: bump SDK build tools to 34.0.0

- docker/ubuntu/baseimage-20.04/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/104)
> baseimage-20.04: minor cleanup

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/virdevenv/109)
> Fix: Update a link in readme
